In [13]:
# Create Array
import numpy as np
width=8
height=4
random_array = np.random.randint(0,7, size=(4,8))
print(random_array)

[[6 4 0 4 1 4 5 5]
 [4 1 6 6 5 1 2 0]
 [3 0 3 5 0 2 5 6]
 [0 1 1 2 6 2 4 3]]


In [14]:
# Create Normal Vector
flat_array = random_array.flatten()
magnitude = np.linalg.norm(flat_array)
normalized_array = flat_array / magnitude
normal_vector = normalized_array[:32]
print(normal_vector)

[0.2883416  0.19222773 0.         0.19222773 0.04805693 0.19222773
 0.24028467 0.24028467 0.19222773 0.04805693 0.2883416  0.2883416
 0.24028467 0.04805693 0.09611387 0.         0.1441708  0.
 0.1441708  0.24028467 0.         0.09611387 0.24028467 0.2883416
 0.         0.04805693 0.04805693 0.09611387 0.2883416  0.09611387
 0.19222773 0.1441708 ]


In [15]:
# Import
from qiskit import QuantumCircuit, Aer, transpile, assemble
from qiskit.visualization import plot_histogram

In [16]:
# Encoding
num_qubits = len(normal_vector)
theta_values = 2 * np.arcsin(normal_vector)
qc = QuantumCircuit(num_qubits)
for i in range(num_qubits):
    qc.ry(theta_values[i], i)

# Draw
qc.draw()

┌─────────────┐ 
 q_0: ┤ Ry(0.58499) ├─
      ├─────────────┤ 
 q_1: ┤ Ry(0.38686) ├─
      └──┬───────┬──┘ 
 q_2: ───┤ Ry(0) ├────
      ┌──┴───────┴──┐ 
 q_3: ┤ Ry(0.38686) ├─
      ├─────────────┴┐
 q_4: ┤ Ry(0.096151) ├
      ├─────────────┬┘
 q_5: ┤ Ry(0.38686) ├─
      ├─────────────┤ 
 q_6: ┤ Ry(0.48532) ├─
      ├─────────────┤ 
 q_7: ┤ Ry(0.48532) ├─
      ├─────────────┤ 
 q_8: ┤ Ry(0.38686) ├─
      ├─────────────┴┐
 q_9: ┤ Ry(0.096151) ├
      ├─────────────┬┘
q_10: ┤ Ry(0.58499) ├─
      ├─────────────┤ 
q_11: ┤ Ry(0.58499) ├─
      ├─────────────┤ 
q_12: ┤ Ry(0.48532) ├─
      ├─────────────┴┐
q_13: ┤ Ry(0.096151) ├
      ├─────────────┬┘
q_14: ┤ Ry(0.19252) ├─
      └──┬───────┬──┘ 
q_15: ───┤ Ry(0) ├────
      ┌──┴───────┴──┐ 
q_16: ┤ Ry(0.28935) ├─
      └──┬───────┬──┘ 
q_17: ───┤ Ry(0) ├────
      ┌──┴───────┴──┐ 
q_18: ┤ Ry(0.28935) ├─
      ├─────────────┤ 
q_19: ┤ Ry(0.48532) ├─
      └──┬───────┬──┘ 
q_20: ───┤ Ry(0) ├────
      ┌──┴───────┴──┐ 
q_21: ┤ Ry(0.19252) ├─
      ├─────────────┤ 
q_22: ┤ Ry(0.48532) ├─
      ├─────────────┤ 
q_23: ┤ Ry(0.58499) ├─
      └──┬───────┬──┘ 
q_24: ───┤ Ry(0) ├────
      ┌──┴───────┴───┐
q_25: ┤ Ry(0.096151) ├
      ├──────────────┤
q_26: ┤ Ry(0.096151) ├
      ├─────────────┬┘
q_27: ┤ Ry(0.19252) ├─
      ├─────────────┤ 
q_28: ┤ Ry(0.58499) ├─
      ├─────────────┤ 
q_29: ┤ Ry(0.19252) ├─
      ├─────────────┤ 
q_30: ┤ Ry(0.38686) ├─
      ├─────────────┤ 
q_31: ┤ Ry(0.28935) ├─
      └─────────────┘